"""Initial migration

Revision ID: 04dde15b09a5
Revises: 6b809fda0034
Create Date: 2025-11-20 02:22:24.355199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dde15b09a5'
down_revision = '6b809fda0034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###