"""Initial migration

Revision ID: 074420b9eb0a
Revises: d06d30d15800
Create Date: 2025-11-20 02:31:16.308504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074420b9eb0a'
down_revision = 'd06d30d15800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###