"""Initial migration

Revision ID: 07d8ab0b6018
Revises: 9047407fe76b
Create Date: 2025-11-21 04:18:45.944567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d8ab0b6018'
down_revision = '9047407fe76b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###