"""Initial migration

Revision ID: 0fb56720f939
Revises: a882fd4e2b7e
Create Date: 2025-11-22 05:06:30.453526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb56720f939'
down_revision = 'a882fd4e2b7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###