"""Initial migration

Revision ID: 1b7d1d59fec2
Revises: 469c595b5775
Create Date: 2025-11-20 00:06:31.718412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7d1d59fec2'
down_revision = '469c595b5775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###