"""Initial migration

Revision ID: 25e3cd9bbc44
Revises: 6de2c7bf3d0d
Create Date: 2025-11-20 04:04:23.560512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e3cd9bbc44'
down_revision = '6de2c7bf3d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###