"""Initial migration

Revision ID: 27366a6b8c26
Revises: c66f0a4daab9
Create Date: 2025-11-21 05:32:57.705444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27366a6b8c26'
down_revision = 'c66f0a4daab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###