"""Initial migration

Revision ID: 3112048f95f5
Revises: 074420b9eb0a
Create Date: 2025-11-20 02:31:55.962535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3112048f95f5'
down_revision = '074420b9eb0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###