"""Initial migration

Revision ID: 33e0414013f0
Revises: d717d3d6e587
Create Date: 2025-11-20 02:43:31.322634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e0414013f0'
down_revision = 'd717d3d6e587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###