"""Initial migration

Revision ID: 3a1d40a7d960
Revises: d32dfe8249fc
Create Date: 2025-11-22 05:39:11.569489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1d40a7d960'
down_revision = 'd32dfe8249fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###