"""Initial migration

Revision ID: 3f38e7cc7ce5
Revises: 25e3cd9bbc44
Create Date: 2025-11-20 17:12:27.784713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f38e7cc7ce5'
down_revision = '25e3cd9bbc44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###