"""Initial migration

Revision ID: 427c61104ead
Revises: 3f38e7cc7ce5
Create Date: 2025-11-20 18:00:45.518355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427c61104ead'
down_revision = '3f38e7cc7ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###