"""Initial migration

Revision ID: 43ffe686bf7e
Revises: fd999263f613
Create Date: 2025-11-22 04:08:39.794174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ffe686bf7e'
down_revision = 'fd999263f613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###