"""Initial migration

Revision ID: 4675027fd206
Revises: fe76bf726aed
Create Date: 2025-11-22 20:37:55.997205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4675027fd206'
down_revision = 'fe76bf726aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###