"""Initial migration

Revision ID: 469c595b5775
Revises: cfdeaa702f8b
Create Date: 2025-11-19 23:27:04.274933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469c595b5775'
down_revision = 'cfdeaa702f8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###