"""Initial migration

Revision ID: 6b809fda0034
Revises: aec8a2788c75
Create Date: 2025-11-20 01:59:55.141751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b809fda0034'
down_revision = 'aec8a2788c75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###