"""Initial migration

Revision ID: 6de2c7bf3d0d
Revises: e60fccac1be6
Create Date: 2025-11-20 03:47:21.697951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de2c7bf3d0d'
down_revision = 'e60fccac1be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###