"""initial_schema

Revision ID: 724271220063
Revises: 
Create Date: 2025-11-23 01:53:27.188410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724271220063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('outing_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('capacity_type', sa.String(length=20), nullable=False),
    sa.Column('is_overnight', sa.Boolean(), nullable=False),
    sa.Column('outing_lead_name', sa.String(length=255), nullable=True),
    sa.Column('outing_lead_email', sa.String(length=255), nullable=True),
    sa.Column('outing_lead_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outings_end_date'), 'outings', ['end_date'], unique=False)
    op.create_index(op.f('ix_outings_id'), 'outings', ['id'], unique=False)
    op.create_index(op.f('ix_outings_outing_date'), 'outings', ['outing_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_initial_admin', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('member_type', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('troop_number', sa.String(length=50), nullable=True),
    sa.Column('patrol_name', sa.String(length=100), nullable=True),
    sa.Column('has_youth_protection', sa.Boolean(), nullable=False),
    sa.Column('youth_protection_expiration', sa.Date(), nullable=True),
    sa.Column('vehicle_capacity', sa.Integer(), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_gender'), 'family_members', ['gender'], unique=False)
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index(op.f('ix_family_members_member_type'), 'family_members', ['member_type'], unique=False)
    op.create_index(op.f('ix_family_members_troop_number'), 'family_members', ['troop_number'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outing_id', sa.UUID(), nullable=False),
    sa.Column('family_contact_name', sa.String(length=255), nullable=False),
    sa.Column('family_contact_email', sa.String(length=255), nullable=False),
    sa.Column('family_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outing_id'], ['outings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_id'), 'signups', ['id'], unique=False)
    op.create_index(op.f('ix_signups_outing_id'), 'signups', ['outing_id'], unique=False)
    op.create_table('family_member_allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('allergy', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_member_allergies_family_member_id'), 'family_member_allergies', ['family_member_id'], unique=False)
    op.create_index(op.f('ix_family_member_allergies_id'), 'family_member_allergies', ['id'], unique=False)
    op.create_table('family_member_dietary_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('preference', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_member_dietary_preferences_family_member_id'), 'family_member_dietary_preferences', ['family_member_id'], unique=False)
    op.create_index(op.f('ix_family_member_dietary_preferences_id'), 'family_member_dietary_preferences', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signup_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_family_member_id'), 'participants', ['family_member_id'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_participants_signup_id'), 'participants', ['signup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_signup_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_family_member_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_family_member_dietary_preferences_id'), table_name='family_member_dietary_preferences')
    op.drop_index(op.f('ix_family_member_dietary_preferences_family_member_id'), table_name='family_member_dietary_preferences')
    op.drop_table('family_member_dietary_preferences')
    op.drop_index(op.f('ix_family_member_allergies_id'), table_name='family_member_allergies')
    op.drop_index(op.f('ix_family_member_allergies_family_member_id'), table_name='family_member_allergies')
    op.drop_table('family_member_allergies')
    op.drop_index(op.f('ix_signups_outing_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_id'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_troop_number'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_member_type'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_gender'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outings_outing_date'), table_name='outings')
    op.drop_index(op.f('ix_outings_id'), table_name='outings')
    op.drop_index(op.f('ix_outings_end_date'), table_name='outings')
    op.drop_table('outings')
    # ### end Alembic commands ###