"""Initial migration

Revision ID: 837da24ec268
Revises: 07d8ab0b6018
Create Date: 2025-11-21 05:30:27.884568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837da24ec268'
down_revision = '07d8ab0b6018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###