"""Initial migration

Revision ID: 892d9f2e7930
Revises: 29b51c0fcf54
Create Date: 2025-11-20 01:52:54.754015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892d9f2e7930'
down_revision = '29b51c0fcf54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'capacity_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'capacity_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'fixed'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###