"""Initial migration

Revision ID: 99a314a17023
Revises: b4f2abbc0ef4
Create Date: 2025-11-20 02:47:08.299692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a314a17023'
down_revision = 'b4f2abbc0ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###