"""Initial migration

Revision ID: 9a22878ad46e
Revises: c355d6f11e61
Create Date: 2025-11-20 02:27:18.025292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a22878ad46e'
down_revision = 'c355d6f11e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###