"""Initial migration

Revision ID: a5590743c626
Revises: 9c10d32310d8
Create Date: 2025-11-22 21:55:39.609610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5590743c626'
down_revision = '9c10d32310d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###