"""Initial migration

Revision ID: aec8a2788c75
Revises: af9946e18d06
Create Date: 2025-11-20 01:59:27.853761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec8a2788c75'
down_revision = 'af9946e18d06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###