"""Initial migration

Revision ID: af9946e18d06
Revises: 892d9f2e7930
Create Date: 2025-11-20 01:56:59.036553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9946e18d06'
down_revision = '892d9f2e7930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###