"""Initial migration

Revision ID: b4f2abbc0ef4
Revises: f75e5dda1794
Create Date: 2025-11-20 02:46:45.167142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f2abbc0ef4'
down_revision = 'f75e5dda1794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###