"""Initial migration

Revision ID: c355d6f11e61
Revises: 04dde15b09a5
Create Date: 2025-11-20 02:23:16.576905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c355d6f11e61'
down_revision = '04dde15b09a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###