"""Initial migration

Revision ID: c66f0a4daab9
Revises: 837da24ec268
Create Date: 2025-11-21 05:31:41.064906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66f0a4daab9'
down_revision = '837da24ec268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###