"""Initial migration

Revision ID: cfdeaa702f8b
Revises: b64598a48c63
Create Date: 2025-11-19 23:25:10.446736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdeaa702f8b'
down_revision = 'b64598a48c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###