"""Initial migration

Revision ID: d06d30d15800
Revises: 9a22878ad46e
Create Date: 2025-11-20 02:28:18.120542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d30d15800'
down_revision = '9a22878ad46e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###