"""Initial migration

Revision ID: d32dfe8249fc
Revises: b4d04516ae79
Create Date: 2025-11-22 05:31:54.240718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32dfe8249fc'
down_revision = 'b4d04516ae79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###