"""Initial migration

Revision ID: d5f4bd58053a
Revises: ec7f33fc02f6
Create Date: 2025-11-20 02:35:56.550142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f4bd58053a'
down_revision = 'ec7f33fc02f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###