"""Initial migration

Revision ID: d717d3d6e587
Revises: d5f4bd58053a
Create Date: 2025-11-20 02:36:32.490175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd717d3d6e587'
down_revision = 'd5f4bd58053a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###