"""Initial migration

Revision ID: df10c5dec5ce
Revises: 3a1d40a7d960
Create Date: 2025-11-22 05:41:40.672826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df10c5dec5ce'
down_revision = '3a1d40a7d960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###