"""Initial migration

Revision ID: e60fccac1be6
Revises: 99a314a17023
Create Date: 2025-11-20 03:03:15.054496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60fccac1be6'
down_revision = '99a314a17023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###