"""Initial migration

Revision ID: f75e5dda1794
Revises: 33e0414013f0
Create Date: 2025-11-20 02:43:57.103285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75e5dda1794'
down_revision = '33e0414013f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###