"""Initial migration

Revision ID: fd28cb74d190
Revises: a5590743c626
Create Date: 2025-11-22 21:57:38.890711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd28cb74d190'
down_revision = 'a5590743c626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###