#!/bin/bash

# Shared utility functions for bootstrap scripts
# Source this file in other scripts: source "$(dirname "$0")/lib_utils.sh"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

print_header() {
    echo -e "${CYAN}$1${NC}"
}

print_question() {
    echo -e "${BLUE}? $1${NC}"
}

# Function to check if Docker is installed
check_docker() {
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker Desktop first:"
        echo "   https://www.docker.com/products/docker-desktop"
        return 1
    fi
    return 0
}

# Function to detect Docker Compose command
get_docker_compose() {
    if command -v docker-compose &> /dev/null; then
        echo "docker-compose"
    elif docker compose version &> /dev/null 2>&1; then
        echo "docker compose"
    else
        print_error "Docker Compose is not available. Please install Docker Compose."
        return 1
    fi
}

# Function to generate a random password
generate_password() {
    local length=${1:-16}
    openssl rand -hex "$length"
}

# Function to generate a random secret key
generate_secret() {
    openssl rand -hex 32
}

# Function to generate a random base64 key
generate_base64_secret() {
    openssl rand -base64 60 | tr -d '\n'
}

# Function to read from a config file (first non-comment, non-empty line)
read_config_file() {
    local file="$1"
    if [ -f "$file" ]; then
        grep -v '^#' "$file" | grep -v '^$' | head -n 1 | tr -d '\n\r'
    fi
}

# Function to save value to a config file with header
save_config_file() {
    local file="$1"
    local value="$2"
    local description="$3"
    
    cat > "$file" << EOF
# $description
# Generated by bootstrap.sh on $(date)
# First non-comment, non-empty line is used as the value

$value
EOF
}

# Function to add file to .gitignore if not present
add_to_gitignore() {
    local file="$1"
    if ! grep -q "^$file\$" .gitignore 2>/dev/null; then
        echo "$file" >> .gitignore
        print_success "Added $file to .gitignore"
    fi
}

# Function to validate email format
validate_email() {
    local email="$1"
    if [[ "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        return 0
    else
        return 1
    fi
}

# Function to extract domain from URI
extract_domain() {
    local uri="$1"
    echo "$uri" | sed -e 's|^[^/]*//||' -e 's|/.*$||'
}
